export default function LoremIpsum() {
    return <>
        <h3>Lorem Ipsum</h3>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a venenatis magna. Nullam imperdiet aliquam ante porta molestie. Maecenas vitae suscipit elit, in lobortis orci. Sed non fringilla lorem. Vivamus lacinia leo magna, in porttitor ipsum pellentesque vel. Vestibulum imperdiet, nisl id tristique pretium, libero risus pulvinar ante, a mollis nunc turpis nec enim. Nulla aliquet lacus at ligula accumsan venenatis. In dictum interdum porta. Nam condimentum, dui sed sodales imperdiet, ipsum nunc lacinia risus, convallis blandit ipsum enim sit amet nisi. Aenean iaculis ante a turpis ultrices suscipit. In mollis rhoncus orci, non gravida nunc cursus malesuada. Nunc a risus leo. Etiam viverra felis maximus est fringilla sagittis. Aenean hendrerit eros nec tortor elementum elementum. Aliquam tempus id sem sodales sodales. In fringilla laoreet neque, non sagittis risus finibus id.

            Donec condimentum ut velit quis lacinia. Integer fermentum, nisl et facilisis laoreet, mauris massa tincidunt mauris, sit amet porta leo mauris et purus. Nam id gravida magna, id fermentum dolor. Maecenas vel justo interdum, aliquam arcu a, tincidunt ipsum. Cras ipsum lorem, congue eu libero sit amet, porttitor convallis velit. Morbi ac eros in tortor vehicula iaculis. Praesent et imperdiet libero. Integer eget metus nec libero porttitor fringilla. Vestibulum eleifend est in turpis rutrum feugiat. Suspendisse nec scelerisque dui.

            Integer enim sem, pellentesque non eleifend vitae, lobortis vel diam. Cras vulputate tincidunt quam non faucibus. Nullam eu leo a ipsum mattis consectetur et eu leo. Pellentesque elementum id nisi fringilla congue. Phasellus placerat tellus eget lacinia placerat. Quisque mattis, nunc vel cursus aliquam, sapien arcu pretium turpis, ornare dapibus ipsum elit sed lorem. Curabitur eget imperdiet velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris id faucibus est.

            Sed eleifend dictum enim. Aenean pulvinar hendrerit mi sed scelerisque. Integer ut purus pharetra, convallis risus ut, pellentesque orci. Proin luctus mauris eget leo scelerisque vulputate. Mauris facilisis dui id velit aliquam vehicula id elementum odio. Donec mollis mauris condimentum pharetra euismod. Fusce cursus fringilla magna, eget varius sapien viverra eget.

            Sed varius sed ante lacinia molestie. Etiam sit amet ex sit amet metus lobortis fringilla ac vitae magna. Integer interdum ex vitae metus scelerisque convallis. Aliquam bibendum sed est eget viverra. Sed tempor est ut metus ultricies vehicula. Curabitur pellentesque risus eu mi maximus lobortis. Nam eleifend neque nec velit convallis, in rutrum velit tempus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque laoreet consectetur nunc, vel vulputate est maximus non. Mauris convallis massa et lectus dignissim eleifend. Maecenas cursus leo ut dignissim tincidunt. Integer venenatis, nisl sit amet pretium dictum, tortor lacus cursus ex, eu vehicula velit ante quis purus.</p>
    </>
}